# Flag variables
JC = javac
JR = java

# Clear default targets
.SUFFIXES: .java .class

compile: DueDateCalculator.java
	$(JC) DueDateCalculator.java

run:
	$(JR) DueDateCalculator

clean:
	$(RM) *.class